steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', "-t", "gcr.io/$PROJECT_ID/$BRANCH_NAME:$SHORT_SHA", '.']
      
  - name: gcr.io/cloud-builders/docker
    args: ['push', "gcr.io/$PROJECT_ID/$BRANCH_NAME:$SHORT_SHA"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: [ "run", "deploy", "$BRANCH_NAME", "--image", "gcr.io/$PROJECT_ID/$BRANCH_NAME:$SHORT_SHA", "--region", "asia-southeast2", "--port", "8080", "--allow-unauthenticated"]

timeout: 1600s
images:
  - "gcr.io/$PROJECT_ID/$BRANCH_NAME:$SHORT_SHA"